### ISSUE TITLE
回到Windows后屏幕显示异常

### ISSUE THREAD

**Issue by Optimistices** [xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools#1]
屏幕亮度无法调节
睡眠模式消失
Windows UI显示部分异常

**Comment by xiaoMGitHub** [comment]
什么机型

**Comment by Optimistices** [comment]
Y7000P 2019 PG0 (i5-9300H)

**Comment by xiaoMGitHub** [comment]
在群里测试了半年多，没有机友反馈存在这个问题，可能主板烧了或者是操作问题

**Comment by Optimistices** [comment]
有恢复脚本吗

**Comment by Optimistices** [comment]
对了，BIOS Switchable Graphics 模式 进入Windows，任务管理器内GPU栏没有核显，只有N卡。并且睡眠模式消失
![image](https://user-images.githubusercontent.com/60458634/109407218-f3bb9680-79b9-11eb-8cce-e1db45b696a2.png)
![image](https://user-images.githubusercontent.com/60458634/109407243-26658f00-79ba-11eb-91ce-4d84cc6bda10.png)

**Comment by xiaoMGitHub** [comment]
肯定是操作问题了，进BIOS按F9恢复默认即可

**Comment by Optimistices** [comment]
F9用过了，还是一样。重刷了一遍BIOS，在Discrete Graphics独显模式下恢复正常，但当再选择Switchable Graphics核显混合模式仍旧有此问题

**Comment by xiaoMGitHub** [comment]
你的问题在于连独显模式和混合模式都没理解，建议咨询联想售后让专业人士跟你讲解什么是独显模式什么是混合模式

**Comment by Optimistices** [comment]
好家伙不解决问题也不要直接推锅&close issue吧，你这口吻分明也不知道switchable graphics模式下有GPU0 INTEL核显和GPU1 NVIDIA独显，而用过脚本后BIOS设置成switchable graphics模式后只有GPU0 NVIDIA。我已经排除了其他问题，我想可能如果用恢复脚本可能会解决这个问题，因为这个脚本改的是BIOS高级模式下的设置选项，而19款之后无法在BIOS中还原，F9也无用。既然写了BIOS修改脚本，写一个恢复脚本顺便完善一下feature不是更香嘛

**Comment by xiaoMGitHub** [comment]
问题是我的脚本不修改显卡模式，你所提及的问题与我无关，看样子你也不明白脚本所提供的修改选项修改了什么，已经它的运行原理，当然我也没义务告知
