### ISSUE TITLE
Sleep power issue after use this scrips

### ISSUE THREAD

**Issue by hmthang96** [xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools#2]
When I used this scrips to mod bios to use Bigsur, i got a problem with sleep. It consumed more power than before. When I turned my device to Windows OS, sleep mode on window consumed 5-10%/hour.
 I set bios to default by press F9 but it still consumes too much. I tested on Y530 and Y545, and they have same problem.
Could you have a scrip to restore setting ? , I saw the backup folder, but i don't know to use this

**Comment by xiaoMGitHub** [comment]
This problem should have nothing to do with my script, just enter the BIOS and press F9 to restore the default.
