### ISSUE TITLE
Illegible Characters in cmd

### ISSUE THREAD

**Issue by misaelvillaverde** [xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools#5]
![image](https://user-images.githubusercontent.com/30275501/116817580-a8924100-ab2c-11eb-9493-a49a6eb7d6e9.png)
![image](https://user-images.githubusercontent.com/30275501/116817583-b21ba900-ab2c-11eb-96d3-c182fc221337.png)

**Comment by f2quantum** [comment]
You may not have a Chinese character library installed

---

**Here is my translation：**
Echo 1, 8 generation intel processor installation 10.15+ must be performed
echo.
Echo 2: Force the trackpad to load
echo.
Echo 3: Turn off BIOS Lock
echo.
Echo 4: Turn off CFG Lock
echo.
Echo 5. Modify the DVMT to 64M
echo.
Echo 6. Turn off the lightning safety feature
echo.
Echo 0, exit
echo.
